### ISSUE TITLE
Fehler beim Ausführen

### ISSUE THREAD

**Issue by LeShoe** [LeShoe/CorviOfChaos#2]
Aufruf scheitert mit:

```
Traceback (most recent call last):
  File "Main.py", line 178, in <module>
    Lobby = Room("Lobby","Rooms/klassenzimmer_test_0.png")
  File "Main.py", line 28, in __init__
    self.background = pygame.image.load(skin)
pygame.error: Couldn't open Rooms/klassenzimmer_test_0.png
```

**Comment by DerWe** [comment]
Alles gut. Jetzt geht es
